import type { ProcessNodeType } from './types';

export const BasicMap: Record<string, ProcessNodeType> = {
  'start': {
    status: 'completed',
    name: '开始',
    canUndo: false,
    canDelete: false,
    prevNodes: [],
    nextNodes: ['mid_0', 'mid_1', 'mid_2', 'mid_3', 'mid_4'],
    id: 'start',
    visible: true,
  },
  'mid_1': {
    status: 'in_progress',
    name: '中间节点',
    canUndo: true,
    canDelete: true,
    prevNodes: ['start'],
    nextNodes: ['mid_1_1'],
    id: 'mid_1',
    visible: true,
  },
  'mid_2': {
    status: 'in_progress',
    name: '中间节点',
    canUndo: true,
    canDelete: true,
    prevNodes: ['start'],
    nextNodes: ['end'],
    id: 'mid_2',
    visible: true,
  },
  'mid_3': {
    status: 'in_progress',
    name: '中间节点',
    canUndo: true,
    canDelete: true,
    prevNodes: ['start'],
    nextNodes: ['end'],
    id: 'mid_3',
    visible: true,
  },
  'mid_0': {
    status: 'in_progress',
    name: '中间节点',
    canUndo: true,
    canDelete: true,
    prevNodes: ['start'],
    nextNodes: ['end'],
    id: 'mid_0',
    visible: true,
  },
  'mid_1_1': {
    status: 'in_progress',
    name: '中间节点',
    canUndo: true,
    canDelete: true,
    prevNodes: ['mid_1'],
    nextNodes: ['end'],
    id: 'mid_1_1',
    visible: true,
  },
  'mid_4': {
    status: 'in_progress',
    name: '中间节点',
    canUndo: true,
    canDelete: true,
    prevNodes: ['start'],
    nextNodes: ['end'],
    id: 'mid_4',
    visible: true,
  },
  'end': {
    status: 'pending',
    name: '结束',
    canUndo: true,
    canDelete: false,
    prevNodes: ['mid_0', 'mid_1_1', 'mid_2', 'mid_3', 'mid_4'],
    nextNodes: [],
    id: 'end',
    visible: true,
  }
}

export const TestMap: Record<string, ProcessNodeType> = {
  'start': {
    id: 'start',
    name: '开始',
    visible: true,
    status: 'completed',
    canDelete: false,
    canUndo: false,
    prevNodes: [],
    nextNodes: ['mid_2','mid_1'],
  },
    'mid_1': {
    id: 'mid_1',
    name: '中间节点1',
    visible: true,
    status: 'in_progress',
    canDelete: true,
    canUndo: true,
    prevNodes: ['start'],
    nextNodes: ['end', 'mid_2'],
  },
  'mid_2': {
    id: 'mid_2',
    name: '中间节点2',
    visible: true,
    status: 'in_progress',
    canDelete: true,
    canUndo: true,
    prevNodes: ['start', 'mid_1'],
    nextNodes: ['end'],
  },
  'end': {
    id: 'end',
    name: '结束',
    visible: true,
    status: 'pending',
    canDelete: false,
    canUndo: true,
    prevNodes: ['mid_1', 'mid_2'],
    nextNodes: [],
  },
}